backend:
  name: github
  repo: Second-City-Prints/wearescp
  branch: main
  site_domain: mystifying-bassi-b743b3.netlify.app

media_folder: "img/uploads"
site_url: http://scpreview.secondcityprints.mobi
show_preview_links: false

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - name: featured_image
        label: Featured image
        widget: object
        fields:
          - {name: src, label: Image, widget: image}
          - {name: alt, label: Alt text, widget: string}
          - {name: sizing, label: sizing, widget: select,  options: [ "auto", "cover", "contain"], default: "auto", hint: "This determines how the image is sized. Cover will expand and crop the image to fit as needed, contain will ensure the whole image will fit in the banner space but may lead to black bars on the sides to offset the empty space, and finally auto will just have it be 100% the width of the banner space, with the height just being whatever it takes up when it's scaled to fit the width. You can usually just go with auto."}
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }      

  - name: "artists"
    label: "Artists"
    folder: "_artists"
    create: true
    slug: "{{name}}"
    fields: 
      - {label: "Artist Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image", hint: "This is the main image used by the artist. It appears in the scrolling portion at the top, and the gallery."}
      - {label: "Order", name: "order", widget: "number", default: 10, value_type: "int", hint: "You can use this number to set the ideal position this artist appears. Lower is closer to the top/left. You don't have to set this if you don't care, it's sorted automatically."}
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        summary: '{{fields.image}}'
        fields: 
          - {label: "Image", name: "image", widget: "image"}
          - {label: "URL", name: "url", widget: "string", required: false}